name: Run Python Script

on:
  push:
    branches:
      - main # Or whatever branch you want to trigger on

jobs:
  run_script:
    runs-on: ubuntu-latest # Or windows-latest or macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or a specific version, like '3.9'

      - name: Install dependencies (if needed)
        run: |
          python -m pip install --upgrade pip
          # python -m pip install <your_dependencies>

      - name: Execute Python Script
        run: python app.py
